# Generated by Django 4.1.7 on 2023-03-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('image', models.URLField(default='https://shecodes.com.au/wp-content/uploads/2020/02/Purple_no_circle.svg')),
                ('event_type', models.CharField(choices=[('Flash', 'Flash'), ('Plus', 'Plus'), ('One Day Workshop', 'One Day Workshop')], max_length=200, null=True)),
                ('location', models.CharField(choices=[('Sydney', 'Sydney'), ('Perth', 'Perth'), ('Brisbane', 'Brisbane')], max_length=200, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField()),
                ('image', models.URLField(default='https://shecodes.com.au/wp-content/uploads/2021/10/Screen-Shot-2021-12-07-at-12.00.01-pm-400x400.png')),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Industry', 'Industry'), ('Lead', 'Lead')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tech_Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.BooleanField()),
                ('offer', models.BooleanField()),
                ('contract_sent', models.BooleanField()),
                ('contract_return', models.BooleanField()),
                ('onboarding_completed', models.BooleanField()),
                ('feedback', models.BooleanField()),
                ('offboarding', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.event')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='mentor.mentor')),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_tech_stack',
            field=models.ManyToManyField(related_name='tech_mentor', to='mentor.tech_stack'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_tech_stack',
            field=models.ManyToManyField(related_name='events_tech', to='mentor.tech_stack'),
        ),
        migrations.AddField(
            model_name='event',
            name='mentors',
            field=models.ManyToManyField(related_name='events', through='mentor.Onboarding', to='mentor.mentor'),
        ),
    ]
