# Generated by Django 4.1.7 on 2023-03-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='https://shecodes.com.au/wp-content/uploads/2020/02/Purple_no_circle.svg')),
                ('event_type', models.CharField(choices=[('Flash', 'Flash'), ('Plus', 'Plus'), ('One Day Workshop', 'One Day Workshop')], max_length=200, null=True)),
                ('location', models.CharField(choices=[('Sydney', 'Sydney'), ('Perth', 'Perth'), ('Brisbane', 'Brisbane')], max_length=200, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('image', models.URLField(default='https://shecodes.com.au/wp-content/uploads/2021/10/Screen-Shot-2021-12-07-at-12.00.01-pm-400x400.png')),
                ('skills', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Industry', 'Industry'), ('Lead', 'Lead')], max_length=200, null=True)),
                ('interview', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('contract_sent', models.BooleanField(default=False)),
                ('contract_return', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('feedback_sent', models.BooleanField(default=False)),
                ('offboarding', models.BooleanField(default=False)),
                ('events', models.ManyToManyField(blank=True, related_name='mentors', to='mentor.event')),
            ],
        ),
    ]
