# Generated by Django 4.1.7 on 2023-03-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mentors',
            field=models.ManyToManyField(related_name='events', to='mentor.mentor'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
