# Generated by Django 4.1.7 on 2023-04-01 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='can_travel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='location',
            field=models.CharField(choices=[('Sydney', 'Sydney'), ('Perth', 'Perth'), ('Brisbane', 'Brisbane')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor.event'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='mentor.mentor'),
        ),
    ]
