# Generated by Django 4.1.7 on 2023-04-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentor_can_travel_mentor_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
