# Generated by Django 4.1.7 on 2023-04-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_stack',
            name='image',
            field=models.URLField(default='https://tinyurl.com/mvtwxmr5'),
        ),
    ]
