# Generated by Django 4.1.7 on 2023-03-23 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_alter_event_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='event',
        ),
        migrations.AddField(
            model_name='mentor',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='mentor.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 12, 36, 29, 825409)),
        ),
    ]
