# Generated by Django 4.1.7 on 2023-04-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_tech_stack_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_stack',
            name='image',
            field=models.URLField(default='shorturl.at/lxP34'),
        ),
    ]
